drop table users if exists;

create table users
(
   id NUMBER(10,0) NOT NULL AUTO_INCREMENT,
   name VARCHAR2(255) DEFAULT NOT NULL,
   email VARCHAR2(255) DEFAULT NOT NULL,
   primary key(id)
);

DROP SEQUENCE USER_SEQUENCE_ID if exists;

CREATE SEQUENCE USER_SEQUENCE_ID
  MINVALUE 1
  MAXVALUE 9999999999999999
  START WITH 1
  INCREMENT BY 100
  CACHE 100;

DROP TABLE PRODUCT if exists;

CREATE TABLE PRODUCT (
ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
DESCRIPTION VARCHAR2(255) DEFAULT NULL,
IMAGE_URL VARCHAR2(255) DEFAULT NULL,
PRICE NUMBER(19,2) DEFAULT NULL,
PRODUCT_ID VARCHAR2(255) DEFAULT NULL,
VERSION NUMBER(10, 0) DEFAULT NULL,
PRIMARY KEY (ID));

DROP SEQUENCE PRODUCT_SEQUENCE_ID if exists;

CREATE SEQUENCE PRODUCT_SEQUENCE_ID
  MINVALUE 1
  MAXVALUE 9999999999999999
  START WITH 1
  INCREMENT BY 100
  CACHE 100;